# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.add_responder_to_alert_payload_all_of import AddResponderToAlertPayloadAllOf
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server.models.recipient import Recipient
from openapi_server import util

from openapi_server.models.add_responder_to_alert_payload_all_of import AddResponderToAlertPayloadAllOf  # noqa: E501
from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501
from openapi_server.models.recipient import Recipient  # noqa: E501

class AddResponderToAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, responder=None):  # noqa: E501
        """AddResponderToAlertPayload - a model defined in OpenAPI

        :param user: The user of this AddResponderToAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this AddResponderToAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this AddResponderToAlertPayload.  # noqa: E501
        :type source: str
        :param responder: The responder of this AddResponderToAlertPayload.  # noqa: E501
        :type responder: Recipient
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'responder': Recipient
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'responder': 'responder'
        }

        self._user = user
        self._note = note
        self._source = source
        self._responder = responder

    @classmethod
    def from_dict(cls, dikt) -> 'AddResponderToAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddResponderToAlertPayload of this AddResponderToAlertPayload.  # noqa: E501
        :rtype: AddResponderToAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AddResponderToAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this AddResponderToAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AddResponderToAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this AddResponderToAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this AddResponderToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this AddResponderToAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this AddResponderToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this AddResponderToAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this AddResponderToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this AddResponderToAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AddResponderToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this AddResponderToAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def responder(self):
        """Gets the responder of this AddResponderToAlertPayload.


        :return: The responder of this AddResponderToAlertPayload.
        :rtype: Recipient
        """
        return self._responder

    @responder.setter
    def responder(self, responder):
        """Sets the responder of this AddResponderToAlertPayload.


        :param responder: The responder of this AddResponderToAlertPayload.
        :type responder: Recipient
        """
        if responder is None:
            raise ValueError("Invalid value for `responder`, must not be `None`")  # noqa: E501

        self._responder = responder
