# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.add_tags_to_alert_payload_all_of import AddTagsToAlertPayloadAllOf
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server import util

from openapi_server.models.add_tags_to_alert_payload_all_of import AddTagsToAlertPayloadAllOf  # noqa: E501
from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501

class AddTagsToAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, tags=None):  # noqa: E501
        """AddTagsToAlertPayload - a model defined in OpenAPI

        :param user: The user of this AddTagsToAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this AddTagsToAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this AddTagsToAlertPayload.  # noqa: E501
        :type source: str
        :param tags: The tags of this AddTagsToAlertPayload.  # noqa: E501
        :type tags: List[str]
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'tags': List[str]
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'tags': 'tags'
        }

        self._user = user
        self._note = note
        self._source = source
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'AddTagsToAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddTagsToAlertPayload of this AddTagsToAlertPayload.  # noqa: E501
        :rtype: AddTagsToAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AddTagsToAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this AddTagsToAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AddTagsToAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this AddTagsToAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this AddTagsToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this AddTagsToAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this AddTagsToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this AddTagsToAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this AddTagsToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this AddTagsToAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AddTagsToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this AddTagsToAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def tags(self):
        """Gets the tags of this AddTagsToAlertPayload.


        :return: The tags of this AddTagsToAlertPayload.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AddTagsToAlertPayload.


        :param tags: The tags of this AddTagsToAlertPayload.
        :type tags: List[str]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
