# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.add_details_to_alert_payload_all_of import AddDetailsToAlertPayloadAllOf
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server import util

from openapi_server.models.add_details_to_alert_payload_all_of import AddDetailsToAlertPayloadAllOf  # noqa: E501
from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501

class AddDetailsToAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, details=None):  # noqa: E501
        """AddDetailsToAlertPayload - a model defined in OpenAPI

        :param user: The user of this AddDetailsToAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this AddDetailsToAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this AddDetailsToAlertPayload.  # noqa: E501
        :type source: str
        :param details: The details of this AddDetailsToAlertPayload.  # noqa: E501
        :type details: Dict[str, str]
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'details': Dict[str, str]
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'details': 'details'
        }

        self._user = user
        self._note = note
        self._source = source
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'AddDetailsToAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddDetailsToAlertPayload of this AddDetailsToAlertPayload.  # noqa: E501
        :rtype: AddDetailsToAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AddDetailsToAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this AddDetailsToAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AddDetailsToAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this AddDetailsToAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this AddDetailsToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this AddDetailsToAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this AddDetailsToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this AddDetailsToAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this AddDetailsToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this AddDetailsToAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AddDetailsToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this AddDetailsToAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def details(self):
        """Gets the details of this AddDetailsToAlertPayload.

        Key-value pairs to add as custom property into alert.  # noqa: E501

        :return: The details of this AddDetailsToAlertPayload.
        :rtype: Dict[str, str]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this AddDetailsToAlertPayload.

        Key-value pairs to add as custom property into alert.  # noqa: E501

        :param details: The details of this AddDetailsToAlertPayload.
        :type details: Dict[str, str]
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details
