# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AddDetailsToAlertPayloadAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, details=None):  # noqa: E501
        """AddDetailsToAlertPayloadAllOf - a model defined in OpenAPI

        :param details: The details of this AddDetailsToAlertPayloadAllOf.  # noqa: E501
        :type details: Dict[str, str]
        """
        self.openapi_types = {
            'details': Dict[str, str]
        }

        self.attribute_map = {
            'details': 'details'
        }

        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'AddDetailsToAlertPayloadAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddDetailsToAlertPayload_allOf of this AddDetailsToAlertPayloadAllOf.  # noqa: E501
        :rtype: AddDetailsToAlertPayloadAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def details(self):
        """Gets the details of this AddDetailsToAlertPayloadAllOf.

        Key-value pairs to add as custom property into alert.  # noqa: E501

        :return: The details of this AddDetailsToAlertPayloadAllOf.
        :rtype: Dict[str, str]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this AddDetailsToAlertPayloadAllOf.

        Key-value pairs to add as custom property into alert.  # noqa: E501

        :param details: The details of this AddDetailsToAlertPayloadAllOf.
        :type details: Dict[str, str]
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details
