# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.add_team_to_alert_payload_all_of import AddTeamToAlertPayloadAllOf
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server.models.team_recipient import TeamRecipient
from openapi_server import util

from openapi_server.models.add_team_to_alert_payload_all_of import AddTeamToAlertPayloadAllOf  # noqa: E501
from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501
from openapi_server.models.team_recipient import TeamRecipient  # noqa: E501

class AddTeamToAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, team=None):  # noqa: E501
        """AddTeamToAlertPayload - a model defined in OpenAPI

        :param user: The user of this AddTeamToAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this AddTeamToAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this AddTeamToAlertPayload.  # noqa: E501
        :type source: str
        :param team: The team of this AddTeamToAlertPayload.  # noqa: E501
        :type team: TeamRecipient
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'team': TeamRecipient
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'team': 'team'
        }

        self._user = user
        self._note = note
        self._source = source
        self._team = team

    @classmethod
    def from_dict(cls, dikt) -> 'AddTeamToAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddTeamToAlertPayload of this AddTeamToAlertPayload.  # noqa: E501
        :rtype: AddTeamToAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AddTeamToAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this AddTeamToAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AddTeamToAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this AddTeamToAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this AddTeamToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this AddTeamToAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this AddTeamToAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this AddTeamToAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this AddTeamToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this AddTeamToAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AddTeamToAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this AddTeamToAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def team(self):
        """Gets the team of this AddTeamToAlertPayload.


        :return: The team of this AddTeamToAlertPayload.
        :rtype: TeamRecipient
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this AddTeamToAlertPayload.


        :param team: The team of this AddTeamToAlertPayload.
        :type team: TeamRecipient
        """
        if team is None:
            raise ValueError("Invalid value for `team`, must not be `None`")  # noqa: E501

        self._team = team
