# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AddTagsToAlertPayloadAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tags=None):  # noqa: E501
        """AddTagsToAlertPayloadAllOf - a model defined in OpenAPI

        :param tags: The tags of this AddTagsToAlertPayloadAllOf.  # noqa: E501
        :type tags: List[str]
        """
        self.openapi_types = {
            'tags': List[str]
        }

        self.attribute_map = {
            'tags': 'tags'
        }

        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'AddTagsToAlertPayloadAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddTagsToAlertPayload_allOf of this AddTagsToAlertPayloadAllOf.  # noqa: E501
        :rtype: AddTagsToAlertPayloadAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tags(self):
        """Gets the tags of this AddTagsToAlertPayloadAllOf.


        :return: The tags of this AddTagsToAlertPayloadAllOf.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AddTagsToAlertPayloadAllOf.


        :param tags: The tags of this AddTagsToAlertPayloadAllOf.
        :type tags: List[str]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
