# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AlertAttachmentMeta(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, id=None):  # noqa: E501
        """AlertAttachmentMeta - a model defined in OpenAPI

        :param name: The name of this AlertAttachmentMeta.  # noqa: E501
        :type name: str
        :param id: The id of this AlertAttachmentMeta.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'name': str,
            'id': str
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id'
        }

        self._name = name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'AlertAttachmentMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertAttachmentMeta of this AlertAttachmentMeta.  # noqa: E501
        :rtype: AlertAttachmentMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AlertAttachmentMeta.


        :return: The name of this AlertAttachmentMeta.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AlertAttachmentMeta.


        :param name: The name of this AlertAttachmentMeta.
        :type name: str
        """

        self._name = name

    @property
    def id(self):
        """Gets the id of this AlertAttachmentMeta.


        :return: The id of this AlertAttachmentMeta.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertAttachmentMeta.


        :param id: The id of this AlertAttachmentMeta.
        :type id: str
        """

        self._id = id
