# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AlertAttachment(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, url=None):  # noqa: E501
        """AlertAttachment - a model defined in OpenAPI

        :param name: The name of this AlertAttachment.  # noqa: E501
        :type name: str
        :param url: The url of this AlertAttachment.  # noqa: E501
        :type url: str
        """
        self.openapi_types = {
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'name': 'name',
            'url': 'url'
        }

        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'AlertAttachment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertAttachment of this AlertAttachment.  # noqa: E501
        :rtype: AlertAttachment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AlertAttachment.


        :return: The name of this AlertAttachment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AlertAttachment.


        :param name: The name of this AlertAttachment.
        :type name: str
        """

        self._name = name

    @property
    def url(self):
        """Gets the url of this AlertAttachment.


        :return: The url of this AlertAttachment.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AlertAttachment.


        :param url: The url of this AlertAttachment.
        :type url: str
        """

        self._url = url
