# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AlertUserMeta(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, username=None):  # noqa: E501
        """AlertUserMeta - a model defined in OpenAPI

        :param id: The id of this AlertUserMeta.  # noqa: E501
        :type id: str
        :param username: The username of this AlertUserMeta.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'id': str,
            'username': str
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username'
        }

        self._id = id
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'AlertUserMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertUserMeta of this AlertUserMeta.  # noqa: E501
        :rtype: AlertUserMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this AlertUserMeta.


        :return: The id of this AlertUserMeta.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertUserMeta.


        :param id: The id of this AlertUserMeta.
        :type id: str
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this AlertUserMeta.


        :return: The username of this AlertUserMeta.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AlertUserMeta.


        :param username: The username of this AlertUserMeta.
        :type username: str
        """

        self._username = username
