# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_user_meta import AlertUserMeta
from openapi_server import util

from openapi_server.models.alert_user_meta import AlertUserMeta  # noqa: E501

class AlertRecipient(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, state=None, method=None, created_at=None, updated_at=None):  # noqa: E501
        """AlertRecipient - a model defined in OpenAPI

        :param user: The user of this AlertRecipient.  # noqa: E501
        :type user: AlertUserMeta
        :param state: The state of this AlertRecipient.  # noqa: E501
        :type state: str
        :param method: The method of this AlertRecipient.  # noqa: E501
        :type method: str
        :param created_at: The created_at of this AlertRecipient.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this AlertRecipient.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'user': AlertUserMeta,
            'state': str,
            'method': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'user': 'user',
            'state': 'state',
            'method': 'method',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._user = user
        self._state = state
        self._method = method
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'AlertRecipient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertRecipient of this AlertRecipient.  # noqa: E501
        :rtype: AlertRecipient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AlertRecipient.


        :return: The user of this AlertRecipient.
        :rtype: AlertUserMeta
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AlertRecipient.


        :param user: The user of this AlertRecipient.
        :type user: AlertUserMeta
        """

        self._user = user

    @property
    def state(self):
        """Gets the state of this AlertRecipient.


        :return: The state of this AlertRecipient.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AlertRecipient.


        :param state: The state of this AlertRecipient.
        :type state: str
        """

        self._state = state

    @property
    def method(self):
        """Gets the method of this AlertRecipient.


        :return: The method of this AlertRecipient.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this AlertRecipient.


        :param method: The method of this AlertRecipient.
        :type method: str
        """

        self._method = method

    @property
    def created_at(self):
        """Gets the created_at of this AlertRecipient.


        :return: The created_at of this AlertRecipient.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AlertRecipient.


        :param created_at: The created_at of this AlertRecipient.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AlertRecipient.


        :return: The updated_at of this AlertRecipient.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AlertRecipient.


        :param updated_at: The updated_at of this AlertRecipient.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
