# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AlertIntegration(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, type=None):  # noqa: E501
        """AlertIntegration - a model defined in OpenAPI

        :param id: The id of this AlertIntegration.  # noqa: E501
        :type id: str
        :param name: The name of this AlertIntegration.  # noqa: E501
        :type name: str
        :param type: The type of this AlertIntegration.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type'
        }

        self._id = id
        self._name = name
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'AlertIntegration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertIntegration of this AlertIntegration.  # noqa: E501
        :rtype: AlertIntegration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this AlertIntegration.


        :return: The id of this AlertIntegration.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AlertIntegration.


        :param id: The id of this AlertIntegration.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AlertIntegration.


        :return: The name of this AlertIntegration.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AlertIntegration.


        :param name: The name of this AlertIntegration.
        :type name: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this AlertIntegration.


        :return: The type of this AlertIntegration.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AlertIntegration.


        :param type: The type of this AlertIntegration.
        :type type: str
        """

        self._type = type
