# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AlertPaging(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first=None, next=None):  # noqa: E501
        """AlertPaging - a model defined in OpenAPI

        :param first: The first of this AlertPaging.  # noqa: E501
        :type first: str
        :param next: The next of this AlertPaging.  # noqa: E501
        :type next: str
        """
        self.openapi_types = {
            'first': str,
            'next': str
        }

        self.attribute_map = {
            'first': 'first',
            'next': 'next'
        }

        self._first = first
        self._next = next

    @classmethod
    def from_dict(cls, dikt) -> 'AlertPaging':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AlertPaging of this AlertPaging.  # noqa: E501
        :rtype: AlertPaging
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first(self):
        """Gets the first of this AlertPaging.


        :return: The first of this AlertPaging.
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this AlertPaging.


        :param first: The first of this AlertPaging.
        :type first: str
        """

        self._first = first

    @property
    def next(self):
        """Gets the next of this AlertPaging.


        :return: The next of this AlertPaging.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this AlertPaging.


        :param next: The next of this AlertPaging.
        :type next: str
        """

        self._next = next
