# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server.models.assign_alert_payload_all_of import AssignAlertPayloadAllOf
from openapi_server.models.user_recipient import UserRecipient
from openapi_server import util

from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501
from openapi_server.models.assign_alert_payload_all_of import AssignAlertPayloadAllOf  # noqa: E501
from openapi_server.models.user_recipient import UserRecipient  # noqa: E501

class AssignAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, owner=None):  # noqa: E501
        """AssignAlertPayload - a model defined in OpenAPI

        :param user: The user of this AssignAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this AssignAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this AssignAlertPayload.  # noqa: E501
        :type source: str
        :param owner: The owner of this AssignAlertPayload.  # noqa: E501
        :type owner: UserRecipient
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'owner': UserRecipient
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'owner': 'owner'
        }

        self._user = user
        self._note = note
        self._source = source
        self._owner = owner

    @classmethod
    def from_dict(cls, dikt) -> 'AssignAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AssignAlertPayload of this AssignAlertPayload.  # noqa: E501
        :rtype: AssignAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this AssignAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this AssignAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AssignAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this AssignAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this AssignAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this AssignAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this AssignAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this AssignAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this AssignAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this AssignAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this AssignAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this AssignAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def owner(self):
        """Gets the owner of this AssignAlertPayload.


        :return: The owner of this AssignAlertPayload.
        :rtype: UserRecipient
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AssignAlertPayload.


        :param owner: The owner of this AssignAlertPayload.
        :type owner: UserRecipient
        """
        if owner is None:
            raise ValueError("Invalid value for `owner`, must not be `None`")  # noqa: E501

        self._owner = owner
