# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BaseResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, took=0.0):  # noqa: E501
        """BaseResponse - a model defined in OpenAPI

        :param request_id: The request_id of this BaseResponse.  # noqa: E501
        :type request_id: str
        :param took: The took of this BaseResponse.  # noqa: E501
        :type took: float
        """
        self.openapi_types = {
            'request_id': str,
            'took': float
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'took': 'took'
        }

        self._request_id = request_id
        self._took = took

    @classmethod
    def from_dict(cls, dikt) -> 'BaseResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseResponse of this BaseResponse.  # noqa: E501
        :rtype: BaseResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self):
        """Gets the request_id of this BaseResponse.


        :return: The request_id of this BaseResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this BaseResponse.


        :param request_id: The request_id of this BaseResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def took(self):
        """Gets the took of this BaseResponse.


        :return: The took of this BaseResponse.
        :rtype: float
        """
        return self._took

    @took.setter
    def took(self, took):
        """Sets the took of this BaseResponse.


        :param took: The took of this BaseResponse.
        :type took: float
        """
        if took is None:
            raise ValueError("Invalid value for `took`, must not be `None`")  # noqa: E501

        self._took = took
