# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.saved_search_meta import SavedSearchMeta
from openapi_server import util

from openapi_server.models.saved_search_meta import SavedSearchMeta  # noqa: E501

class CreateSavedSearchResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """CreateSavedSearchResponseAllOf - a model defined in OpenAPI

        :param data: The data of this CreateSavedSearchResponseAllOf.  # noqa: E501
        :type data: SavedSearchMeta
        """
        self.openapi_types = {
            'data': SavedSearchMeta
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CreateSavedSearchResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateSavedSearchResponse_allOf of this CreateSavedSearchResponseAllOf.  # noqa: E501
        :rtype: CreateSavedSearchResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CreateSavedSearchResponseAllOf.


        :return: The data of this CreateSavedSearchResponseAllOf.
        :rtype: SavedSearchMeta
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CreateSavedSearchResponseAllOf.


        :param data: The data of this CreateSavedSearchResponseAllOf.
        :type data: SavedSearchMeta
        """

        self._data = data
