# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.heartbeat import Heartbeat
from openapi_server import util

from openapi_server.models.heartbeat import Heartbeat  # noqa: E501

class CreateHeartbeatResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """CreateHeartbeatResponseAllOf - a model defined in OpenAPI

        :param data: The data of this CreateHeartbeatResponseAllOf.  # noqa: E501
        :type data: Heartbeat
        """
        self.openapi_types = {
            'data': Heartbeat
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CreateHeartbeatResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateHeartbeatResponse_allOf of this CreateHeartbeatResponseAllOf.  # noqa: E501
        :rtype: CreateHeartbeatResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CreateHeartbeatResponseAllOf.


        :return: The data of this CreateHeartbeatResponseAllOf.
        :rtype: Heartbeat
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CreateHeartbeatResponseAllOf.


        :param data: The data of this CreateHeartbeatResponseAllOf.
        :type data: Heartbeat
        """

        self._data = data
