# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ErrorResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None, code=None, response_headers=None):  # noqa: E501
        """ErrorResponseAllOf - a model defined in OpenAPI

        :param message: The message of this ErrorResponseAllOf.  # noqa: E501
        :type message: str
        :param code: The code of this ErrorResponseAllOf.  # noqa: E501
        :type code: int
        :param response_headers: The response_headers of this ErrorResponseAllOf.  # noqa: E501
        :type response_headers: Dict[str, List[str]]
        """
        self.openapi_types = {
            'message': str,
            'code': int,
            'response_headers': Dict[str, List[str]]
        }

        self.attribute_map = {
            'message': 'message',
            'code': 'code',
            'response_headers': 'responseHeaders'
        }

        self._message = message
        self._code = code
        self._response_headers = response_headers

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse_allOf of this ErrorResponseAllOf.  # noqa: E501
        :rtype: ErrorResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self):
        """Gets the message of this ErrorResponseAllOf.


        :return: The message of this ErrorResponseAllOf.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorResponseAllOf.


        :param message: The message of this ErrorResponseAllOf.
        :type message: str
        """

        self._message = message

    @property
    def code(self):
        """Gets the code of this ErrorResponseAllOf.


        :return: The code of this ErrorResponseAllOf.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorResponseAllOf.


        :param code: The code of this ErrorResponseAllOf.
        :type code: int
        """

        self._code = code

    @property
    def response_headers(self):
        """Gets the response_headers of this ErrorResponseAllOf.


        :return: The response_headers of this ErrorResponseAllOf.
        :rtype: Dict[str, List[str]]
        """
        return self._response_headers

    @response_headers.setter
    def response_headers(self, response_headers):
        """Sets the response_headers of this ErrorResponseAllOf.


        :param response_headers: The response_headers of this ErrorResponseAllOf.
        :type response_headers: Dict[str, List[str]]
        """

        self._response_headers = response_headers
