# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.escalation_recipient import EscalationRecipient
from openapi_server import util

from openapi_server.models.escalation_recipient import EscalationRecipient  # noqa: E501

class EscalateAlertToNextPayloadAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, escalation=None):  # noqa: E501
        """EscalateAlertToNextPayloadAllOf - a model defined in OpenAPI

        :param escalation: The escalation of this EscalateAlertToNextPayloadAllOf.  # noqa: E501
        :type escalation: EscalationRecipient
        """
        self.openapi_types = {
            'escalation': EscalationRecipient
        }

        self.attribute_map = {
            'escalation': 'escalation'
        }

        self._escalation = escalation

    @classmethod
    def from_dict(cls, dikt) -> 'EscalateAlertToNextPayloadAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EscalateAlertToNextPayload_allOf of this EscalateAlertToNextPayloadAllOf.  # noqa: E501
        :rtype: EscalateAlertToNextPayloadAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def escalation(self):
        """Gets the escalation of this EscalateAlertToNextPayloadAllOf.


        :return: The escalation of this EscalateAlertToNextPayloadAllOf.
        :rtype: EscalationRecipient
        """
        return self._escalation

    @escalation.setter
    def escalation(self, escalation):
        """Sets the escalation of this EscalateAlertToNextPayloadAllOf.


        :param escalation: The escalation of this EscalateAlertToNextPayloadAllOf.
        :type escalation: EscalationRecipient
        """
        if escalation is None:
            raise ValueError("Invalid value for `escalation`, must not be `None`")  # noqa: E501

        self._escalation = escalation
