# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server.models.escalate_alert_to_next_payload_all_of import EscalateAlertToNextPayloadAllOf
from openapi_server.models.escalation_recipient import EscalationRecipient
from openapi_server import util

from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501
from openapi_server.models.escalate_alert_to_next_payload_all_of import EscalateAlertToNextPayloadAllOf  # noqa: E501
from openapi_server.models.escalation_recipient import EscalationRecipient  # noqa: E501

class EscalateAlertToNextPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, escalation=None):  # noqa: E501
        """EscalateAlertToNextPayload - a model defined in OpenAPI

        :param user: The user of this EscalateAlertToNextPayload.  # noqa: E501
        :type user: str
        :param note: The note of this EscalateAlertToNextPayload.  # noqa: E501
        :type note: str
        :param source: The source of this EscalateAlertToNextPayload.  # noqa: E501
        :type source: str
        :param escalation: The escalation of this EscalateAlertToNextPayload.  # noqa: E501
        :type escalation: EscalationRecipient
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'escalation': EscalationRecipient
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'escalation': 'escalation'
        }

        self._user = user
        self._note = note
        self._source = source
        self._escalation = escalation

    @classmethod
    def from_dict(cls, dikt) -> 'EscalateAlertToNextPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EscalateAlertToNextPayload of this EscalateAlertToNextPayload.  # noqa: E501
        :rtype: EscalateAlertToNextPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this EscalateAlertToNextPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this EscalateAlertToNextPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this EscalateAlertToNextPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this EscalateAlertToNextPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this EscalateAlertToNextPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this EscalateAlertToNextPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this EscalateAlertToNextPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this EscalateAlertToNextPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this EscalateAlertToNextPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this EscalateAlertToNextPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this EscalateAlertToNextPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this EscalateAlertToNextPayload.
        :type source: str
        """

        self._source = source

    @property
    def escalation(self):
        """Gets the escalation of this EscalateAlertToNextPayload.


        :return: The escalation of this EscalateAlertToNextPayload.
        :rtype: EscalationRecipient
        """
        return self._escalation

    @escalation.setter
    def escalation(self, escalation):
        """Sets the escalation of this EscalateAlertToNextPayload.


        :param escalation: The escalation of this EscalateAlertToNextPayload.
        :type escalation: EscalationRecipient
        """
        if escalation is None:
            raise ValueError("Invalid value for `escalation`, must not be `None`")  # noqa: E501

        self._escalation = escalation
