# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.get_count_alerts_response_all_of_data import GetCountAlertsResponseAllOfData
from openapi_server import util

from openapi_server.models.get_count_alerts_response_all_of_data import GetCountAlertsResponseAllOfData  # noqa: E501

class GetCountAlertsResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetCountAlertsResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetCountAlertsResponseAllOf.  # noqa: E501
        :type data: GetCountAlertsResponseAllOfData
        """
        self.openapi_types = {
            'data': GetCountAlertsResponseAllOfData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetCountAlertsResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCountAlertsResponse_allOf of this GetCountAlertsResponseAllOf.  # noqa: E501
        :rtype: GetCountAlertsResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetCountAlertsResponseAllOf.


        :return: The data of this GetCountAlertsResponseAllOf.
        :rtype: GetCountAlertsResponseAllOfData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetCountAlertsResponseAllOf.


        :param data: The data of this GetCountAlertsResponseAllOf.
        :type data: GetCountAlertsResponseAllOfData
        """

        self._data = data
