# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.saved_search import SavedSearch
from openapi_server import util

from openapi_server.models.saved_search import SavedSearch  # noqa: E501

class GetSavedSearchResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetSavedSearchResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetSavedSearchResponseAllOf.  # noqa: E501
        :type data: SavedSearch
        """
        self.openapi_types = {
            'data': SavedSearch
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetSavedSearchResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetSavedSearchResponse_allOf of this GetSavedSearchResponseAllOf.  # noqa: E501
        :rtype: GetSavedSearchResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetSavedSearchResponseAllOf.


        :return: The data of this GetSavedSearchResponseAllOf.
        :rtype: SavedSearch
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetSavedSearchResponseAllOf.


        :param data: The data of this GetSavedSearchResponseAllOf.
        :type data: SavedSearch
        """

        self._data = data
