# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_attachment import AlertAttachment
from openapi_server import util

from openapi_server.models.alert_attachment import AlertAttachment  # noqa: E501

class GetAlertAttachmentResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetAlertAttachmentResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetAlertAttachmentResponseAllOf.  # noqa: E501
        :type data: AlertAttachment
        """
        self.openapi_types = {
            'data': AlertAttachment
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAlertAttachmentResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAlertAttachmentResponse_allOf of this GetAlertAttachmentResponseAllOf.  # noqa: E501
        :rtype: GetAlertAttachmentResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetAlertAttachmentResponseAllOf.


        :return: The data of this GetAlertAttachmentResponseAllOf.
        :rtype: AlertAttachment
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetAlertAttachmentResponseAllOf.


        :param data: The data of this GetAlertAttachmentResponseAllOf.
        :type data: AlertAttachment
        """

        self._data = data
