# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.incident_request_status import IncidentRequestStatus
from openapi_server import util

from openapi_server.models.incident_request_status import IncidentRequestStatus  # noqa: E501

class GetIncidentRequestStatusResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetIncidentRequestStatusResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetIncidentRequestStatusResponseAllOf.  # noqa: E501
        :type data: IncidentRequestStatus
        """
        self.openapi_types = {
            'data': IncidentRequestStatus
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetIncidentRequestStatusResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetIncidentRequestStatusResponse_allOf of this GetIncidentRequestStatusResponseAllOf.  # noqa: E501
        :rtype: GetIncidentRequestStatusResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetIncidentRequestStatusResponseAllOf.


        :return: The data of this GetIncidentRequestStatusResponseAllOf.
        :rtype: IncidentRequestStatus
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetIncidentRequestStatusResponseAllOf.


        :param data: The data of this GetIncidentRequestStatusResponseAllOf.
        :type data: IncidentRequestStatus
        """

        self._data = data
