# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.incident import Incident
from openapi_server import util

from openapi_server.models.incident import Incident  # noqa: E501

class GetIncidentResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetIncidentResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetIncidentResponseAllOf.  # noqa: E501
        :type data: Incident
        """
        self.openapi_types = {
            'data': Incident
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetIncidentResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetIncidentResponse_allOf of this GetIncidentResponseAllOf.  # noqa: E501
        :rtype: GetIncidentResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetIncidentResponseAllOf.


        :return: The data of this GetIncidentResponseAllOf.
        :rtype: Incident
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetIncidentResponseAllOf.


        :param data: The data of this GetIncidentResponseAllOf.
        :type data: Incident
        """

        self._data = data
