# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.account_info import AccountInfo
from openapi_server import util

from openapi_server.models.account_info import AccountInfo  # noqa: E501

class GetAccountInfoResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetAccountInfoResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetAccountInfoResponseAllOf.  # noqa: E501
        :type data: AccountInfo
        """
        self.openapi_types = {
            'data': AccountInfo
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAccountInfoResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAccountInfoResponse_allOf of this GetAccountInfoResponseAllOf.  # noqa: E501
        :rtype: GetAccountInfoResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetAccountInfoResponseAllOf.


        :return: The data of this GetAccountInfoResponseAllOf.
        :rtype: AccountInfo
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetAccountInfoResponseAllOf.


        :param data: The data of this GetAccountInfoResponseAllOf.
        :type data: AccountInfo
        """

        self._data = data
