# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_request_status import AlertRequestStatus
from openapi_server import util

from openapi_server.models.alert_request_status import AlertRequestStatus  # noqa: E501

class GetRequestStatusResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetRequestStatusResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetRequestStatusResponseAllOf.  # noqa: E501
        :type data: AlertRequestStatus
        """
        self.openapi_types = {
            'data': AlertRequestStatus
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetRequestStatusResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetRequestStatusResponse_allOf of this GetRequestStatusResponseAllOf.  # noqa: E501
        :rtype: GetRequestStatusResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetRequestStatusResponseAllOf.


        :return: The data of this GetRequestStatusResponseAllOf.
        :rtype: AlertRequestStatus
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetRequestStatusResponseAllOf.


        :param data: The data of this GetRequestStatusResponseAllOf.
        :type data: AlertRequestStatus
        """

        self._data = data
