# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert import Alert
from openapi_server import util

from openapi_server.models.alert import Alert  # noqa: E501

class GetAlertResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """GetAlertResponseAllOf - a model defined in OpenAPI

        :param data: The data of this GetAlertResponseAllOf.  # noqa: E501
        :type data: Alert
        """
        self.openapi_types = {
            'data': Alert
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAlertResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAlertResponse_allOf of this GetAlertResponseAllOf.  # noqa: E501
        :rtype: GetAlertResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GetAlertResponseAllOf.


        :return: The data of this GetAlertResponseAllOf.
        :rtype: Alert
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GetAlertResponseAllOf.


        :param data: The data of this GetAlertResponseAllOf.
        :type data: Alert
        """

        self._data = data
