# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class IncidentRequestStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, action=None, processed_at=None, integration_id=None, is_success=None, status=None, incident_id=None):  # noqa: E501
        """IncidentRequestStatus - a model defined in OpenAPI

        :param success: The success of this IncidentRequestStatus.  # noqa: E501
        :type success: bool
        :param action: The action of this IncidentRequestStatus.  # noqa: E501
        :type action: str
        :param processed_at: The processed_at of this IncidentRequestStatus.  # noqa: E501
        :type processed_at: datetime
        :param integration_id: The integration_id of this IncidentRequestStatus.  # noqa: E501
        :type integration_id: str
        :param is_success: The is_success of this IncidentRequestStatus.  # noqa: E501
        :type is_success: bool
        :param status: The status of this IncidentRequestStatus.  # noqa: E501
        :type status: str
        :param incident_id: The incident_id of this IncidentRequestStatus.  # noqa: E501
        :type incident_id: str
        """
        self.openapi_types = {
            'success': bool,
            'action': str,
            'processed_at': datetime,
            'integration_id': str,
            'is_success': bool,
            'status': str,
            'incident_id': str
        }

        self.attribute_map = {
            'success': 'success',
            'action': 'action',
            'processed_at': 'processedAt',
            'integration_id': 'integrationId',
            'is_success': 'isSuccess',
            'status': 'status',
            'incident_id': 'incidentId'
        }

        self._success = success
        self._action = action
        self._processed_at = processed_at
        self._integration_id = integration_id
        self._is_success = is_success
        self._status = status
        self._incident_id = incident_id

    @classmethod
    def from_dict(cls, dikt) -> 'IncidentRequestStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IncidentRequestStatus of this IncidentRequestStatus.  # noqa: E501
        :rtype: IncidentRequestStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self):
        """Gets the success of this IncidentRequestStatus.


        :return: The success of this IncidentRequestStatus.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this IncidentRequestStatus.


        :param success: The success of this IncidentRequestStatus.
        :type success: bool
        """

        self._success = success

    @property
    def action(self):
        """Gets the action of this IncidentRequestStatus.


        :return: The action of this IncidentRequestStatus.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this IncidentRequestStatus.


        :param action: The action of this IncidentRequestStatus.
        :type action: str
        """

        self._action = action

    @property
    def processed_at(self):
        """Gets the processed_at of this IncidentRequestStatus.


        :return: The processed_at of this IncidentRequestStatus.
        :rtype: datetime
        """
        return self._processed_at

    @processed_at.setter
    def processed_at(self, processed_at):
        """Sets the processed_at of this IncidentRequestStatus.


        :param processed_at: The processed_at of this IncidentRequestStatus.
        :type processed_at: datetime
        """

        self._processed_at = processed_at

    @property
    def integration_id(self):
        """Gets the integration_id of this IncidentRequestStatus.


        :return: The integration_id of this IncidentRequestStatus.
        :rtype: str
        """
        return self._integration_id

    @integration_id.setter
    def integration_id(self, integration_id):
        """Sets the integration_id of this IncidentRequestStatus.


        :param integration_id: The integration_id of this IncidentRequestStatus.
        :type integration_id: str
        """

        self._integration_id = integration_id

    @property
    def is_success(self):
        """Gets the is_success of this IncidentRequestStatus.


        :return: The is_success of this IncidentRequestStatus.
        :rtype: bool
        """
        return self._is_success

    @is_success.setter
    def is_success(self, is_success):
        """Sets the is_success of this IncidentRequestStatus.


        :param is_success: The is_success of this IncidentRequestStatus.
        :type is_success: bool
        """

        self._is_success = is_success

    @property
    def status(self):
        """Gets the status of this IncidentRequestStatus.


        :return: The status of this IncidentRequestStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IncidentRequestStatus.


        :param status: The status of this IncidentRequestStatus.
        :type status: str
        """

        self._status = status

    @property
    def incident_id(self):
        """Gets the incident_id of this IncidentRequestStatus.


        :return: The incident_id of this IncidentRequestStatus.
        :rtype: str
        """
        return self._incident_id

    @incident_id.setter
    def incident_id(self, incident_id):
        """Sets the incident_id of this IncidentRequestStatus.


        :param incident_id: The incident_id of this IncidentRequestStatus.
        :type incident_id: str
        """

        self._incident_id = incident_id
