# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.base_incident import BaseIncident
from openapi_server.models.base_response import BaseResponse
from openapi_server.models.list_incidents_response_all_of import ListIncidentsResponseAllOf
from openapi_server.models.page_details import PageDetails
from openapi_server import util

from openapi_server.models.base_incident import BaseIncident  # noqa: E501
from openapi_server.models.base_response import BaseResponse  # noqa: E501
from openapi_server.models.list_incidents_response_all_of import ListIncidentsResponseAllOf  # noqa: E501
from openapi_server.models.page_details import PageDetails  # noqa: E501

class ListIncidentsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, took=0.0, data=None, paging=None):  # noqa: E501
        """ListIncidentsResponse - a model defined in OpenAPI

        :param request_id: The request_id of this ListIncidentsResponse.  # noqa: E501
        :type request_id: str
        :param took: The took of this ListIncidentsResponse.  # noqa: E501
        :type took: float
        :param data: The data of this ListIncidentsResponse.  # noqa: E501
        :type data: List[BaseIncident]
        :param paging: The paging of this ListIncidentsResponse.  # noqa: E501
        :type paging: PageDetails
        """
        self.openapi_types = {
            'request_id': str,
            'took': float,
            'data': List[BaseIncident],
            'paging': PageDetails
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'took': 'took',
            'data': 'data',
            'paging': 'paging'
        }

        self._request_id = request_id
        self._took = took
        self._data = data
        self._paging = paging

    @classmethod
    def from_dict(cls, dikt) -> 'ListIncidentsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListIncidentsResponse of this ListIncidentsResponse.  # noqa: E501
        :rtype: ListIncidentsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self):
        """Gets the request_id of this ListIncidentsResponse.


        :return: The request_id of this ListIncidentsResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this ListIncidentsResponse.


        :param request_id: The request_id of this ListIncidentsResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def took(self):
        """Gets the took of this ListIncidentsResponse.


        :return: The took of this ListIncidentsResponse.
        :rtype: float
        """
        return self._took

    @took.setter
    def took(self, took):
        """Sets the took of this ListIncidentsResponse.


        :param took: The took of this ListIncidentsResponse.
        :type took: float
        """
        if took is None:
            raise ValueError("Invalid value for `took`, must not be `None`")  # noqa: E501

        self._took = took

    @property
    def data(self):
        """Gets the data of this ListIncidentsResponse.


        :return: The data of this ListIncidentsResponse.
        :rtype: List[BaseIncident]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListIncidentsResponse.


        :param data: The data of this ListIncidentsResponse.
        :type data: List[BaseIncident]
        """

        self._data = data

    @property
    def paging(self):
        """Gets the paging of this ListIncidentsResponse.


        :return: The paging of this ListIncidentsResponse.
        :rtype: PageDetails
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this ListIncidentsResponse.


        :param paging: The paging of this ListIncidentsResponse.
        :type paging: PageDetails
        """

        self._paging = paging
