# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_log import AlertLog
from openapi_server.models.alert_paging import AlertPaging
from openapi_server import util

from openapi_server.models.alert_log import AlertLog  # noqa: E501
from openapi_server.models.alert_paging import AlertPaging  # noqa: E501

class ListAlertLogsResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, paging=None):  # noqa: E501
        """ListAlertLogsResponseAllOf - a model defined in OpenAPI

        :param data: The data of this ListAlertLogsResponseAllOf.  # noqa: E501
        :type data: List[AlertLog]
        :param paging: The paging of this ListAlertLogsResponseAllOf.  # noqa: E501
        :type paging: AlertPaging
        """
        self.openapi_types = {
            'data': List[AlertLog],
            'paging': AlertPaging
        }

        self.attribute_map = {
            'data': 'data',
            'paging': 'paging'
        }

        self._data = data
        self._paging = paging

    @classmethod
    def from_dict(cls, dikt) -> 'ListAlertLogsResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAlertLogsResponse_allOf of this ListAlertLogsResponseAllOf.  # noqa: E501
        :rtype: ListAlertLogsResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ListAlertLogsResponseAllOf.


        :return: The data of this ListAlertLogsResponseAllOf.
        :rtype: List[AlertLog]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListAlertLogsResponseAllOf.


        :param data: The data of this ListAlertLogsResponseAllOf.
        :type data: List[AlertLog]
        """

        self._data = data

    @property
    def paging(self):
        """Gets the paging of this ListAlertLogsResponseAllOf.


        :return: The paging of this ListAlertLogsResponseAllOf.
        :rtype: AlertPaging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this ListAlertLogsResponseAllOf.


        :param paging: The paging of this ListAlertLogsResponseAllOf.
        :type paging: AlertPaging
        """

        self._paging = paging
