# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_recipient import AlertRecipient
from openapi_server import util

from openapi_server.models.alert_recipient import AlertRecipient  # noqa: E501

class ListAlertRecipientsResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ListAlertRecipientsResponseAllOf - a model defined in OpenAPI

        :param data: The data of this ListAlertRecipientsResponseAllOf.  # noqa: E501
        :type data: List[AlertRecipient]
        """
        self.openapi_types = {
            'data': List[AlertRecipient]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ListAlertRecipientsResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAlertRecipientsResponse_allOf of this ListAlertRecipientsResponseAllOf.  # noqa: E501
        :rtype: ListAlertRecipientsResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ListAlertRecipientsResponseAllOf.


        :return: The data of this ListAlertRecipientsResponseAllOf.
        :rtype: List[AlertRecipient]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListAlertRecipientsResponseAllOf.


        :param data: The data of this ListAlertRecipientsResponseAllOf.
        :type data: List[AlertRecipient]
        """

        self._data = data
