# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.heartbeat import Heartbeat
from openapi_server import util

from openapi_server.models.heartbeat import Heartbeat  # noqa: E501

class ListHeartbeatResponseAllOfData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, heartbeats=None):  # noqa: E501
        """ListHeartbeatResponseAllOfData - a model defined in OpenAPI

        :param heartbeats: The heartbeats of this ListHeartbeatResponseAllOfData.  # noqa: E501
        :type heartbeats: List[Heartbeat]
        """
        self.openapi_types = {
            'heartbeats': List[Heartbeat]
        }

        self.attribute_map = {
            'heartbeats': 'heartbeats'
        }

        self._heartbeats = heartbeats

    @classmethod
    def from_dict(cls, dikt) -> 'ListHeartbeatResponseAllOfData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListHeartbeatResponse_allOf_data of this ListHeartbeatResponseAllOfData.  # noqa: E501
        :rtype: ListHeartbeatResponseAllOfData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def heartbeats(self):
        """Gets the heartbeats of this ListHeartbeatResponseAllOfData.


        :return: The heartbeats of this ListHeartbeatResponseAllOfData.
        :rtype: List[Heartbeat]
        """
        return self._heartbeats

    @heartbeats.setter
    def heartbeats(self, heartbeats):
        """Sets the heartbeats of this ListHeartbeatResponseAllOfData.


        :param heartbeats: The heartbeats of this ListHeartbeatResponseAllOfData.
        :type heartbeats: List[Heartbeat]
        """

        self._heartbeats = heartbeats
