# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.base_alert import BaseAlert
from openapi_server.models.page_details import PageDetails
from openapi_server import util

from openapi_server.models.base_alert import BaseAlert  # noqa: E501
from openapi_server.models.page_details import PageDetails  # noqa: E501

class ListAlertsResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, paging=None):  # noqa: E501
        """ListAlertsResponseAllOf - a model defined in OpenAPI

        :param data: The data of this ListAlertsResponseAllOf.  # noqa: E501
        :type data: List[BaseAlert]
        :param paging: The paging of this ListAlertsResponseAllOf.  # noqa: E501
        :type paging: PageDetails
        """
        self.openapi_types = {
            'data': List[BaseAlert],
            'paging': PageDetails
        }

        self.attribute_map = {
            'data': 'data',
            'paging': 'paging'
        }

        self._data = data
        self._paging = paging

    @classmethod
    def from_dict(cls, dikt) -> 'ListAlertsResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAlertsResponse_allOf of this ListAlertsResponseAllOf.  # noqa: E501
        :rtype: ListAlertsResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ListAlertsResponseAllOf.


        :return: The data of this ListAlertsResponseAllOf.
        :rtype: List[BaseAlert]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListAlertsResponseAllOf.


        :param data: The data of this ListAlertsResponseAllOf.
        :type data: List[BaseAlert]
        """

        self._data = data

    @property
    def paging(self):
        """Gets the paging of this ListAlertsResponseAllOf.


        :return: The paging of this ListAlertsResponseAllOf.
        :rtype: PageDetails
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this ListAlertsResponseAllOf.


        :param paging: The paging of this ListAlertsResponseAllOf.
        :type paging: PageDetails
        """

        self._paging = paging
