# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_log import AlertLog
from openapi_server.models.alert_paging import AlertPaging
from openapi_server.models.base_response import BaseResponse
from openapi_server.models.list_alert_logs_response_all_of import ListAlertLogsResponseAllOf
from openapi_server import util

from openapi_server.models.alert_log import AlertLog  # noqa: E501
from openapi_server.models.alert_paging import AlertPaging  # noqa: E501
from openapi_server.models.base_response import BaseResponse  # noqa: E501
from openapi_server.models.list_alert_logs_response_all_of import ListAlertLogsResponseAllOf  # noqa: E501

class ListAlertLogsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, took=0.0, data=None, paging=None):  # noqa: E501
        """ListAlertLogsResponse - a model defined in OpenAPI

        :param request_id: The request_id of this ListAlertLogsResponse.  # noqa: E501
        :type request_id: str
        :param took: The took of this ListAlertLogsResponse.  # noqa: E501
        :type took: float
        :param data: The data of this ListAlertLogsResponse.  # noqa: E501
        :type data: List[AlertLog]
        :param paging: The paging of this ListAlertLogsResponse.  # noqa: E501
        :type paging: AlertPaging
        """
        self.openapi_types = {
            'request_id': str,
            'took': float,
            'data': List[AlertLog],
            'paging': AlertPaging
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'took': 'took',
            'data': 'data',
            'paging': 'paging'
        }

        self._request_id = request_id
        self._took = took
        self._data = data
        self._paging = paging

    @classmethod
    def from_dict(cls, dikt) -> 'ListAlertLogsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAlertLogsResponse of this ListAlertLogsResponse.  # noqa: E501
        :rtype: ListAlertLogsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self):
        """Gets the request_id of this ListAlertLogsResponse.


        :return: The request_id of this ListAlertLogsResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this ListAlertLogsResponse.


        :param request_id: The request_id of this ListAlertLogsResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def took(self):
        """Gets the took of this ListAlertLogsResponse.


        :return: The took of this ListAlertLogsResponse.
        :rtype: float
        """
        return self._took

    @took.setter
    def took(self, took):
        """Sets the took of this ListAlertLogsResponse.


        :param took: The took of this ListAlertLogsResponse.
        :type took: float
        """
        if took is None:
            raise ValueError("Invalid value for `took`, must not be `None`")  # noqa: E501

        self._took = took

    @property
    def data(self):
        """Gets the data of this ListAlertLogsResponse.


        :return: The data of this ListAlertLogsResponse.
        :rtype: List[AlertLog]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListAlertLogsResponse.


        :param data: The data of this ListAlertLogsResponse.
        :type data: List[AlertLog]
        """

        self._data = data

    @property
    def paging(self):
        """Gets the paging of this ListAlertLogsResponse.


        :return: The paging of this ListAlertLogsResponse.
        :rtype: AlertPaging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this ListAlertLogsResponse.


        :param paging: The paging of this ListAlertLogsResponse.
        :type paging: AlertPaging
        """

        self._paging = paging
