# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_attachment_meta import AlertAttachmentMeta
from openapi_server import util

from openapi_server.models.alert_attachment_meta import AlertAttachmentMeta  # noqa: E501

class ListAlertAttachmentsResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ListAlertAttachmentsResponseAllOf - a model defined in OpenAPI

        :param data: The data of this ListAlertAttachmentsResponseAllOf.  # noqa: E501
        :type data: List[AlertAttachmentMeta]
        """
        self.openapi_types = {
            'data': List[AlertAttachmentMeta]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ListAlertAttachmentsResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAlertAttachmentsResponse_allOf of this ListAlertAttachmentsResponseAllOf.  # noqa: E501
        :rtype: ListAlertAttachmentsResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ListAlertAttachmentsResponseAllOf.


        :return: The data of this ListAlertAttachmentsResponseAllOf.
        :rtype: List[AlertAttachmentMeta]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ListAlertAttachmentsResponseAllOf.


        :param data: The data of this ListAlertAttachmentsResponseAllOf.
        :type data: List[AlertAttachmentMeta]
        """

        self._data = data
