# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.condition import Condition
from openapi_server.models.filter import Filter
from openapi_server.models.match_any_condition_all_of import MatchAnyConditionAllOf
from openapi_server import util

from openapi_server.models.condition import Condition  # noqa: E501
from openapi_server.models.filter import Filter  # noqa: E501
from openapi_server.models.match_any_condition_all_of import MatchAnyConditionAllOf  # noqa: E501

class MatchAnyCondition(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, conditions=None):  # noqa: E501
        """MatchAnyCondition - a model defined in OpenAPI

        :param type: The type of this MatchAnyCondition.  # noqa: E501
        :type type: str
        :param conditions: The conditions of this MatchAnyCondition.  # noqa: E501
        :type conditions: List[Condition]
        """
        self.openapi_types = {
            'type': str,
            'conditions': List[Condition]
        }

        self.attribute_map = {
            'type': 'type',
            'conditions': 'conditions'
        }

        self._type = type
        self._conditions = conditions

    @classmethod
    def from_dict(cls, dikt) -> 'MatchAnyCondition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchAnyCondition of this MatchAnyCondition.  # noqa: E501
        :rtype: MatchAnyCondition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this MatchAnyCondition.


        :return: The type of this MatchAnyCondition.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MatchAnyCondition.


        :param type: The type of this MatchAnyCondition.
        :type type: str
        """
        allowed_values = ["match-all", "match-any-condition", "match-all-conditions"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def conditions(self):
        """Gets the conditions of this MatchAnyCondition.


        :return: The conditions of this MatchAnyCondition.
        :rtype: List[Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this MatchAnyCondition.


        :param conditions: The conditions of this MatchAnyCondition.
        :type conditions: List[Condition]
        """
        if conditions is not None and len(conditions) < 1:
            raise ValueError("Invalid value for `conditions`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._conditions = conditions
