# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PageDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prev=None, next=None, first=None, last=None):  # noqa: E501
        """PageDetails - a model defined in OpenAPI

        :param prev: The prev of this PageDetails.  # noqa: E501
        :type prev: str
        :param next: The next of this PageDetails.  # noqa: E501
        :type next: str
        :param first: The first of this PageDetails.  # noqa: E501
        :type first: str
        :param last: The last of this PageDetails.  # noqa: E501
        :type last: str
        """
        self.openapi_types = {
            'prev': str,
            'next': str,
            'first': str,
            'last': str
        }

        self.attribute_map = {
            'prev': 'prev',
            'next': 'next',
            'first': 'first',
            'last': 'last'
        }

        self._prev = prev
        self._next = next
        self._first = first
        self._last = last

    @classmethod
    def from_dict(cls, dikt) -> 'PageDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageDetails of this PageDetails.  # noqa: E501
        :rtype: PageDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prev(self):
        """Gets the prev of this PageDetails.


        :return: The prev of this PageDetails.
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this PageDetails.


        :param prev: The prev of this PageDetails.
        :type prev: str
        """

        self._prev = prev

    @property
    def next(self):
        """Gets the next of this PageDetails.


        :return: The next of this PageDetails.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this PageDetails.


        :param next: The next of this PageDetails.
        :type next: str
        """

        self._next = next

    @property
    def first(self):
        """Gets the first of this PageDetails.


        :return: The first of this PageDetails.
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this PageDetails.


        :param first: The first of this PageDetails.
        :type first: str
        """

        self._first = first

    @property
    def last(self):
        """Gets the last of this PageDetails.


        :return: The last of this PageDetails.
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this PageDetails.


        :param last: The last of this PageDetails.
        :type last: str
        """

        self._last = last
