# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.saved_search_entity import SavedSearchEntity
from openapi_server import util

from openapi_server.models.saved_search_entity import SavedSearchEntity  # noqa: E501

class SavedSearch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, created_at=None, updated_at=None, owner=None, teams=None, description=None, query=None):  # noqa: E501
        """SavedSearch - a model defined in OpenAPI

        :param id: The id of this SavedSearch.  # noqa: E501
        :type id: str
        :param name: The name of this SavedSearch.  # noqa: E501
        :type name: str
        :param created_at: The created_at of this SavedSearch.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this SavedSearch.  # noqa: E501
        :type updated_at: datetime
        :param owner: The owner of this SavedSearch.  # noqa: E501
        :type owner: SavedSearchEntity
        :param teams: The teams of this SavedSearch.  # noqa: E501
        :type teams: List[SavedSearchEntity]
        :param description: The description of this SavedSearch.  # noqa: E501
        :type description: str
        :param query: The query of this SavedSearch.  # noqa: E501
        :type query: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'created_at': datetime,
            'updated_at': datetime,
            'owner': SavedSearchEntity,
            'teams': List[SavedSearchEntity],
            'description': str,
            'query': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt',
            'owner': 'owner',
            'teams': 'teams',
            'description': 'description',
            'query': 'query'
        }

        self._id = id
        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._owner = owner
        self._teams = teams
        self._description = description
        self._query = query

    @classmethod
    def from_dict(cls, dikt) -> 'SavedSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SavedSearch of this SavedSearch.  # noqa: E501
        :rtype: SavedSearch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this SavedSearch.


        :return: The id of this SavedSearch.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SavedSearch.


        :param id: The id of this SavedSearch.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SavedSearch.


        :return: The name of this SavedSearch.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SavedSearch.


        :param name: The name of this SavedSearch.
        :type name: str
        """

        self._name = name

    @property
    def created_at(self):
        """Gets the created_at of this SavedSearch.


        :return: The created_at of this SavedSearch.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SavedSearch.


        :param created_at: The created_at of this SavedSearch.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this SavedSearch.


        :return: The updated_at of this SavedSearch.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this SavedSearch.


        :param updated_at: The updated_at of this SavedSearch.
        :type updated_at: datetime
        """

        self._updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this SavedSearch.


        :return: The owner of this SavedSearch.
        :rtype: SavedSearchEntity
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this SavedSearch.


        :param owner: The owner of this SavedSearch.
        :type owner: SavedSearchEntity
        """

        self._owner = owner

    @property
    def teams(self):
        """Gets the teams of this SavedSearch.


        :return: The teams of this SavedSearch.
        :rtype: List[SavedSearchEntity]
        """
        return self._teams

    @teams.setter
    def teams(self, teams):
        """Sets the teams of this SavedSearch.


        :param teams: The teams of this SavedSearch.
        :type teams: List[SavedSearchEntity]
        """

        self._teams = teams

    @property
    def description(self):
        """Gets the description of this SavedSearch.


        :return: The description of this SavedSearch.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SavedSearch.


        :param description: The description of this SavedSearch.
        :type description: str
        """

        self._description = description

    @property
    def query(self):
        """Gets the query of this SavedSearch.


        :return: The query of this SavedSearch.
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this SavedSearch.


        :param query: The query of this SavedSearch.
        :type query: str
        """

        self._query = query
