# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SnoozeAlertPayloadAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, end_time=None):  # noqa: E501
        """SnoozeAlertPayloadAllOf - a model defined in OpenAPI

        :param end_time: The end_time of this SnoozeAlertPayloadAllOf.  # noqa: E501
        :type end_time: datetime
        """
        self.openapi_types = {
            'end_time': datetime
        }

        self.attribute_map = {
            'end_time': 'endTime'
        }

        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'SnoozeAlertPayloadAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SnoozeAlertPayload_allOf of this SnoozeAlertPayloadAllOf.  # noqa: E501
        :rtype: SnoozeAlertPayloadAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def end_time(self):
        """Gets the end_time of this SnoozeAlertPayloadAllOf.

        Date and time that snooze will lose effect  # noqa: E501

        :return: The end_time of this SnoozeAlertPayloadAllOf.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this SnoozeAlertPayloadAllOf.

        Date and time that snooze will lose effect  # noqa: E501

        :param end_time: The end_time of this SnoozeAlertPayloadAllOf.
        :type end_time: datetime
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time
