# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.alert_action_payload import AlertActionPayload
from openapi_server.models.snooze_alert_payload_all_of import SnoozeAlertPayloadAllOf
from openapi_server import util

from openapi_server.models.alert_action_payload import AlertActionPayload  # noqa: E501
from openapi_server.models.snooze_alert_payload_all_of import SnoozeAlertPayloadAllOf  # noqa: E501

class SnoozeAlertPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, note=None, source=None, end_time=None):  # noqa: E501
        """SnoozeAlertPayload - a model defined in OpenAPI

        :param user: The user of this SnoozeAlertPayload.  # noqa: E501
        :type user: str
        :param note: The note of this SnoozeAlertPayload.  # noqa: E501
        :type note: str
        :param source: The source of this SnoozeAlertPayload.  # noqa: E501
        :type source: str
        :param end_time: The end_time of this SnoozeAlertPayload.  # noqa: E501
        :type end_time: datetime
        """
        self.openapi_types = {
            'user': str,
            'note': str,
            'source': str,
            'end_time': datetime
        }

        self.attribute_map = {
            'user': 'user',
            'note': 'note',
            'source': 'source',
            'end_time': 'endTime'
        }

        self._user = user
        self._note = note
        self._source = source
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'SnoozeAlertPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SnoozeAlertPayload of this SnoozeAlertPayload.  # noqa: E501
        :rtype: SnoozeAlertPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this SnoozeAlertPayload.

        Display name of the request owner  # noqa: E501

        :return: The user of this SnoozeAlertPayload.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this SnoozeAlertPayload.

        Display name of the request owner  # noqa: E501

        :param user: The user of this SnoozeAlertPayload.
        :type user: str
        """

        self._user = user

    @property
    def note(self):
        """Gets the note of this SnoozeAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :return: The note of this SnoozeAlertPayload.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this SnoozeAlertPayload.

        Additional note that will be added while creating the alert  # noqa: E501

        :param note: The note of this SnoozeAlertPayload.
        :type note: str
        """

        self._note = note

    @property
    def source(self):
        """Gets the source of this SnoozeAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :return: The source of this SnoozeAlertPayload.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this SnoozeAlertPayload.

        Source field of the alert. Default value is IP address of the incoming request  # noqa: E501

        :param source: The source of this SnoozeAlertPayload.
        :type source: str
        """

        self._source = source

    @property
    def end_time(self):
        """Gets the end_time of this SnoozeAlertPayload.

        Date and time that snooze will lose effect  # noqa: E501

        :return: The end_time of this SnoozeAlertPayload.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this SnoozeAlertPayload.

        Date and time that snooze will lose effect  # noqa: E501

        :param end_time: The end_time of this SnoozeAlertPayload.
        :type end_time: datetime
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time
