# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.status_page_entry_all_of import StatusPageEntryAllOf
from openapi_server import util

from openapi_server.models.status_page_entry_all_of import StatusPageEntryAllOf  # noqa: E501

class StatusPageEntry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, details=None):  # noqa: E501
        """StatusPageEntry - a model defined in OpenAPI

        :param title: The title of this StatusPageEntry.  # noqa: E501
        :type title: str
        :param details: The details of this StatusPageEntry.  # noqa: E501
        :type details: str
        """
        self.openapi_types = {
            'title': str,
            'details': str
        }

        self.attribute_map = {
            'title': 'title',
            'details': 'details'
        }

        self._title = title
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'StatusPageEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StatusPageEntry of this StatusPageEntry.  # noqa: E501
        :rtype: StatusPageEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this StatusPageEntry.

        The message to be added using status page into incident  # noqa: E501

        :return: The title of this StatusPageEntry.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this StatusPageEntry.

        The message to be added using status page into incident  # noqa: E501

        :param title: The title of this StatusPageEntry.
        :type title: str
        """

        self._title = title

    @property
    def details(self):
        """Gets the details of this StatusPageEntry.

        Description of the message being added via stats page into incident  # noqa: E501

        :return: The details of this StatusPageEntry.
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this StatusPageEntry.

        Description of the message being added via stats page into incident  # noqa: E501

        :param details: The details of this StatusPageEntry.
        :type details: str
        """

        self._details = details
