# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.base_response import BaseResponse
from openapi_server.models.success_data import SuccessData
from openapi_server.models.success_response_all_of import SuccessResponseAllOf
from openapi_server import util

from openapi_server.models.base_response import BaseResponse  # noqa: E501
from openapi_server.models.success_data import SuccessData  # noqa: E501
from openapi_server.models.success_response_all_of import SuccessResponseAllOf  # noqa: E501

class SuccessResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, request_id=None, took=0.0, result=None, data=None):  # noqa: E501
        """SuccessResponse - a model defined in OpenAPI

        :param request_id: The request_id of this SuccessResponse.  # noqa: E501
        :type request_id: str
        :param took: The took of this SuccessResponse.  # noqa: E501
        :type took: float
        :param result: The result of this SuccessResponse.  # noqa: E501
        :type result: str
        :param data: The data of this SuccessResponse.  # noqa: E501
        :type data: SuccessData
        """
        self.openapi_types = {
            'request_id': str,
            'took': float,
            'result': str,
            'data': SuccessData
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'took': 'took',
            'result': 'result',
            'data': 'data'
        }

        self._request_id = request_id
        self._took = took
        self._result = result
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse of this SuccessResponse.  # noqa: E501
        :rtype: SuccessResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self):
        """Gets the request_id of this SuccessResponse.


        :return: The request_id of this SuccessResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this SuccessResponse.


        :param request_id: The request_id of this SuccessResponse.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def took(self):
        """Gets the took of this SuccessResponse.


        :return: The took of this SuccessResponse.
        :rtype: float
        """
        return self._took

    @took.setter
    def took(self, took):
        """Sets the took of this SuccessResponse.


        :param took: The took of this SuccessResponse.
        :type took: float
        """
        if took is None:
            raise ValueError("Invalid value for `took`, must not be `None`")  # noqa: E501

        self._took = took

    @property
    def result(self):
        """Gets the result of this SuccessResponse.


        :return: The result of this SuccessResponse.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this SuccessResponse.


        :param result: The result of this SuccessResponse.
        :type result: str
        """

        self._result = result

    @property
    def data(self):
        """Gets the data of this SuccessResponse.


        :return: The data of this SuccessResponse.
        :rtype: SuccessData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SuccessResponse.


        :param data: The data of this SuccessResponse.
        :type data: SuccessData
        """

        self._data = data
