# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.success_data import SuccessData
from openapi_server import util

from openapi_server.models.success_data import SuccessData  # noqa: E501

class SuccessResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None, data=None):  # noqa: E501
        """SuccessResponseAllOf - a model defined in OpenAPI

        :param result: The result of this SuccessResponseAllOf.  # noqa: E501
        :type result: str
        :param data: The data of this SuccessResponseAllOf.  # noqa: E501
        :type data: SuccessData
        """
        self.openapi_types = {
            'result': str,
            'data': SuccessData
        }

        self.attribute_map = {
            'result': 'result',
            'data': 'data'
        }

        self._result = result
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessResponse_allOf of this SuccessResponseAllOf.  # noqa: E501
        :rtype: SuccessResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this SuccessResponseAllOf.


        :return: The result of this SuccessResponseAllOf.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this SuccessResponseAllOf.


        :param result: The result of this SuccessResponseAllOf.
        :type result: str
        """

        self._result = result

    @property
    def data(self):
        """Gets the data of this SuccessResponseAllOf.


        :return: The data of this SuccessResponseAllOf.
        :rtype: SuccessData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SuccessResponseAllOf.


        :param data: The data of this SuccessResponseAllOf.
        :type data: SuccessData
        """

        self._data = data
