# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdateAlertDescriptionPayload(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description=None):  # noqa: E501
        """UpdateAlertDescriptionPayload - a model defined in OpenAPI

        :param description: The description of this UpdateAlertDescriptionPayload.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'description': str
        }

        self.attribute_map = {
            'description': 'description'
        }

        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateAlertDescriptionPayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateAlertDescriptionPayload of this UpdateAlertDescriptionPayload.  # noqa: E501
        :rtype: UpdateAlertDescriptionPayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this UpdateAlertDescriptionPayload.

        Description of the alert  # noqa: E501

        :return: The description of this UpdateAlertDescriptionPayload.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateAlertDescriptionPayload.

        Description of the alert  # noqa: E501

        :param description: The description of this UpdateAlertDescriptionPayload.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description
