# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UserRecipientAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None):  # noqa: E501
        """UserRecipientAllOf - a model defined in OpenAPI

        :param username: The username of this UserRecipientAllOf.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'username': str
        }

        self.attribute_map = {
            'username': 'username'
        }

        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'UserRecipientAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRecipient_allOf of this UserRecipientAllOf.  # noqa: E501
        :rtype: UserRecipientAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this UserRecipientAllOf.


        :return: The username of this UserRecipientAllOf.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserRecipientAllOf.


        :param username: The username of this UserRecipientAllOf.
        :type username: str
        """

        self._username = username
