# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.recipient import Recipient
from openapi_server.models.user_recipient_all_of import UserRecipientAllOf
from openapi_server import util

from openapi_server.models.recipient import Recipient  # noqa: E501
from openapi_server.models.user_recipient_all_of import UserRecipientAllOf  # noqa: E501

class UserRecipient(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, id=None, username=None):  # noqa: E501
        """UserRecipient - a model defined in OpenAPI

        :param type: The type of this UserRecipient.  # noqa: E501
        :type type: str
        :param id: The id of this UserRecipient.  # noqa: E501
        :type id: str
        :param username: The username of this UserRecipient.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'type': str,
            'id': str,
            'username': str
        }

        self.attribute_map = {
            'type': 'type',
            'id': 'id',
            'username': 'username'
        }

        self._type = type
        self._id = id
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'UserRecipient':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRecipient of this UserRecipient.  # noqa: E501
        :rtype: UserRecipient
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this UserRecipient.


        :return: The type of this UserRecipient.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this UserRecipient.


        :param type: The type of this UserRecipient.
        :type type: str
        """
        allowed_values = ["all", "none", "user", "escalation", "schedule", "team", "group"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this UserRecipient.


        :return: The id of this UserRecipient.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserRecipient.


        :param id: The id of this UserRecipient.
        :type id: str
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this UserRecipient.


        :return: The username of this UserRecipient.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserRecipient.


        :param username: The username of this UserRecipient.
        :type username: str
        """

        self._username = username
